//@author h
//@category Export
//@keybinding
//@menupath
//@toolbar

import java.io.File;
import java.io.PrintWriter;
import java.util.Iterator;

import ghidra.app.script.GhidraScript;
import ghidra.program.model.data.*;


public class ExportStructProperties extends GhidraScript {


    @Override
    public void run() throws Exception {


        File out = askFile("Output file", "Save");

        String struct_name = "material_t_u_76_s_0";

        DataTypeManager dtm =
            currentProgram.getDataTypeManager();


        DataType material =
            findDataType(dtm, struct_name);


        if (material == null)
        {
            println("Could not find " + struct_name);
            return;
        }


        if (!(material instanceof Structure))
        {
            println(struct_name + " is not a structure");
            return;
        }


        Structure struct = (Structure) material;


        PrintWriter writer = new PrintWriter(out);


        writer.println("#pragma once");
        writer.println("#include <optional>");
        writer.println("#include \"data_types.h\"");
        writer.println();
        writer.println("// Generated by Ghidra");
        writer.println();


        generateProperties(writer, struct);

        writer.println();

        generateApply(writer, struct);


        writer.close();


        println("Done.");
    }



    private void generateProperties(
        PrintWriter writer,
        Structure struct)
    {

        writer.println("struct " + struct.getName() + "_properties");
        writer.println("{");


        for (DataTypeComponent field : struct.getComponents())
        {

            String name = field.getFieldName();

            if (name == null)
                continue;


            String type =
                typeToCpp(field.getDataType());


            if (!validType(type))
                continue;


            writer.printf(
                "    std::optional<%s> %s;%n",
                type,
                name
            );
        }


        writer.println("};");
    }



    private void generateApply(
        PrintWriter writer,
        Structure struct)
    {

        writer.println(
            "inline void ApplyProperties("
        );

        writer.println(
            "    " + struct.getName() + "& target,"
        );

        writer.println(
            "    const " + struct.getName() + "_properties& props)"
        );

        writer.println("{");


        for (DataTypeComponent field : struct.getComponents())
        {

            String name = field.getFieldName();

            if (name == null)
                continue;


            String type =
                typeToCpp(field.getDataType());


            if (!validType(type))
                continue;


            writer.printf(
                "    if (props.%s)%n",
                name
            );

            writer.printf(
                "        target.%s = *props.%s;%n",
                name,
                name
            );


            writer.println();
        }


        writer.println("}");
    }



    private DataType findDataType(
        DataTypeManager dtm,
        String name)
    {
        Iterator<DataType> it = dtm.getAllDataTypes();
        while (it.hasNext())
        {
            DataType dt = it.next();
            if (dt.getName().equals(name))
                return dt;
        }

        return null;
    }



    private boolean validType(String type)
    {
        if (type.contains("undefined"))
            return false;

        if (type.contains("__"))
            return false;

        return true;
    }



    private String typeToCpp(DataType dt)
    {

        if (dt == null)
            return "void";


        String s = dt.getDisplayName();


        s = s.replace(" *", "*");
        s = s.replace("* ", "*");


        return s;
    }
}