//@author h
//@category Export
//@keybinding
//@menupath
//@toolbar

import java.io.File;
import java.io.PrintWriter;

import ghidra.app.script.GhidraScript;
import ghidra.program.model.listing.*;
import ghidra.program.model.symbol.SourceType;
import ghidra.program.model.data.*;

public class ExportData extends GhidraScript {

    @Override
    public void run() throws Exception {

        File out = askFile("Output file", "Save");

        PrintWriter writer = new PrintWriter(out);

        writer.println("#pragma once");
        writer.println("#include \"data_types.h\"");
        writer.println("// Generated by Ghidra");
        writer.println();

        Listing listing = currentProgram.getListing();

        for (Data d : listing.getDefinedData(true)) {

            String name = d.getLabel();
            String type = typeToCpp(d.getDataType());
            
            long rva =
                d.getAddress().getOffset()
                - currentProgram.getImageBase().getOffset();

            if (name == null || name.isEmpty())
                continue;

            if (type == null || type.isEmpty())
                continue;

            String[] skipped_name_contains = new String[] {
                "__",
                " ",
                "case",
                "pi",
                ".",
                "#"
            };

            String[] skipped_name_startswith = new String[] {
                "FUN_",
                "DAT_",
                "LAB_",
                "off_",
                "unk_",
                "_",
                "switchdata",
                "L_",
                "IMAGE",
                "vftable",
                "total_weight",
                "s_",
            };

            String[] skipped_type_contains = new String[] {
                "[",
                "__",
                "Entry",
                "_ID",
                "Type",
            };

            String[] skipped_type_startswith = new String[] {
                "undefined",
                "RTTI",
                "Terminated",
                "unicode",
                "Image",
                "word",
                "dword",
                "qword",
                "PEx64",
                "_",
            };
    
            boolean skip = false;
            for (String str : skipped_name_contains) {
                if (name.contains(str)) {
                    skip = true;
                    break;
                }
            }
            for (String str : skipped_name_startswith) {
                if (name.startsWith(str)) {
                    skip = true;
                    break;
                }
            }
            for (String str : skipped_type_contains) {
                if (type.contains(str)) {
                    skip = true;
                    break;
                }
            }
            for (String str : skipped_type_startswith) {
                if (type.startsWith(str)) {
                    skip = true;
                    break;
                }
            }
            if (skip)
                continue;

            writer.printf(
                "inline ResolvedData<%s> %s(\"%s\");\n",
                type,
                name,
                name
            );
        }

        writer.close();

        println("Done.");
    }

    private String typeToCpp(DataType dt) {

        if (dt == null)
            return "void";

        String s = dt.getDisplayName();

        s = s.replace(" *", "*");
        s = s.replace("* ", "*");

        return s;
    }
}
