//@author h
//@category Export
//@keybinding
//@menupath
//@toolbar

import java.io.File;
import java.io.PrintWriter;
import java.util.HashMap;
import java.util.Map;

import ghidra.app.script.GhidraScript;
import ghidra.program.model.listing.*;
import ghidra.program.model.data.*;

public class ExportFunctions extends GhidraScript {

    private Map<String, PrintWriter> writers = new HashMap<>();

    @Override
    public void run() throws Exception {

        File outDir = askDirectory("Output directory", "Save");

        String[] categories = {
            "plasmid_api",
            "lua",
            "cells",
            "creatures",
            "mutations",
            "physics",
            "rendering",
            "world",
            "sound",
            "ui",
            "brains",
            "particles",
            "misc"
        };


        // create headers
        for (String category : categories) {

            File file = new File(outDir, category + ".h");

            PrintWriter writer = new PrintWriter(file);

            writer.println("#pragma once");
            writer.println("#include \"..\\data_types.h\"");
            writer.println("#include \"..\\..\\symbol_resolver.h\"");
            writer.println("// Generated by Ghidra");
            writer.println();

            writers.put(category, writer);
        }


        Listing listing = currentProgram.getListing();


        for (Function f : listing.getFunctions(true)) {

            if (shouldSkip(f))
                continue;


            String category = getCategory(f.getName());

            PrintWriter writer = writers.get(category);


            writerFunction(writer, f);
        }


        // close headers
        for (PrintWriter writer : writers.values()) {
            writer.close();
        }


        // generate all.h
        PrintWriter all = new PrintWriter(new File(outDir, "all.h"));

        all.println("#pragma once");
        all.println();

        for (String category : categories) {
            all.println("#include \"" + category + ".h\"");
        }

        all.close();


        println("Done.");
    }


    private boolean shouldSkip(Function f) {

        if (f.isThunk())
            return true;

        if (f.isExternal())
            return true;


        String name = f.getName();


        String[] starts = {
            "FUN_",
            "stb",
            "operator",
            "_",
            "~",
            "`",
            "LZ4_",
            "PTR",
            "UINT",
            "daz"
        };


        String[] contains = {
            "__",
            " ",
            ".",
            "#",
            "$",
            "@",
            "stb_",
            "stbi_",
            "invalid_chunk",
            "vorbis"
        };


        for (String s : starts) {
            if (name.startsWith(s))
                return true;
        }


        for (String s : contains) {
            if (name.contains(s))
                return true;
        }


        String returnType = typeToCpp(f.getReturnType());

        if (returnType.contains("__"))
            return true;

        if (returnType.startsWith("_"))
            return true;


        return false;
    }


    private void writerFunction(PrintWriter writer, Function f) {

        String returnType = typeToCpp(f.getReturnType());


        StringBuilder sigBuilder = new StringBuilder();
        StringBuilder paramsBuilder = new StringBuilder();
        StringBuilder paramsBuilder2 = new StringBuilder();


        sigBuilder.append(returnType);
        sigBuilder.append("(*)(");


        Parameter[] params = f.getParameters();


        for (int i = 0; i < params.length; i++) {

            if (i != 0) {
                sigBuilder.append(", ");
                paramsBuilder.append(", ");
                paramsBuilder2.append(", ");
            }


            String type = typeToCpp(params[i].getDataType());


            sigBuilder.append(type);


            paramsBuilder.append(type);
            paramsBuilder.append(" ");
            paramsBuilder.append(params[i].getName());


            paramsBuilder2.append(params[i].getName());
        }


        sigBuilder.append(")");


        writer.printf(
            "inline %s %s(%s) { return Resolve<%s>(\"%s\")(%s); }\n",
            returnType,
            f.getName(),
            paramsBuilder,
            sigBuilder,
            f.getName(),
            paramsBuilder2
        );
    }



    private String getCategory(String name) {

        name = name.toLowerCase();


        if (containsAny(name,
            "trace_stage",
            "init_materials_list",
            "str_to_id",
            "update_game",
            "update_cells"
            ))
            return "plasmid_api";


        if (containsAny(name,
            "lua"
            ))
            return "lua";


        if (containsAny(name,
            "cell",
            "material"
            ))
            return "cells";


        if (containsAny(name,
            "body",
            "bone",
            "plan",
            "player",
            "creature",
            "piece",
            "material"
            ))
            return "creatures";


        if (containsAny(name,
            "brain",
            "_ai"
            ))
            return "brains";


        if (containsAny(name,
            "mutation"
            ))
            return "mutations";


        if (containsAny(name,
            "particle"
            ))
            return "particles";


        if (containsAny(name,
            "force",
            "velocity",
            "collision",
            "physics",
            "gravity",
            "torque",
            "integrate",
            "oscilator"
            ))
            return "physics";


        if (containsAny(name,
            "render",
            "draw",
            "shader",
            "gl_",
            "camera",
            "texture",
            "frame",
            "icon",
            "window"
            ))
            return "rendering";


        if (containsAny(name,
            "slider",
            "button"
            ))
            return "ui";


        if (containsAny(name,
            "sound",
            "audio"
            ))
            return "sound";


        if (containsAny(name,
            "world",
            "wall",
            "room",
            "flow",
            "map",
            "biome",
            "entrance"
            ))
            return "world";


        return "misc";
    }



    private boolean containsAny(String name, String... words) {

        for (String word : words) {
            if (name.contains(word))
                return true;
        }

        return false;
    }



    private String typeToCpp(DataType dt) {

        if (dt == null)
            return "void";


        String s = dt.getDisplayName();

        s = s.replace(" *", "*");
        s = s.replace("* ", "*");


        return s;
    }
}