LF_POINTER = 0x1000
LF_MODIFIER = 0x1001
LF_PROCEDURE = 0x1008
LF_MFUNCTION = 0x1009
LF_LABEL = 0x000e

LF_ARGLIST = 0x1201
LF_FIELDLIST = 0x1203
LF_ARRAY = 0x1503
LF_CLASS = 0x1504
LF_STRUCTURE = 0x1505
LF_INTERFACE = 0x1519
LF_UNION = 0x1506
LF_ENUM = 0x1507
LF_TYPESERVER2 = 0x1515
LF_VFTABLE = 0x151d
LF_VTSHAPE = 0x000a
LF_BITFIELD = 0x1205
LF_FUNC_ID = 0x1601
LF_MFUNC_ID = 0x1602
LF_BUILDINFO = 0x1603
LF_SUBSTR_LIST = 0x1604
LF_STRING_ID = 0x1605
LF_UDT_SRC_LINE = 0x1606
LF_UDT_MOD_SRC_LINE = 0x1607
LF_METHODLIST = 0x1206
LF_PRECOMP = 0x1509
LF_ENDPRECOMP = 0x0014

# Member Records
LF_BCLASS = 0x1400
LF_BINTERFACE = 0x151a
LF_VBCLASS = 0x1401
LF_IVBCLASS = 0x1402
LF_VFUNCTAB = 0x1409
LF_STMEMBER = 0x150e
LF_METHOD = 0x150f
LF_MEMBER = 0x150d
LF_NESTTYPE = 0x1510
LF_NESTTYPEEX = 0x1512
LF_ONEMETHOD = 0x1511
LF_ENUMERATE = 0x1502
LF_INDEX = 0x1404

TYPE_NAMES = {
	LF_POINTER: "LF_POINTER",
	LF_MODIFIER: "LF_MODIFIER",
	LF_PROCEDURE: "LF_PROCEDURE",
	LF_MFUNCTION: "LF_MFUNCTION",
	LF_LABEL: "LF_LABEL",
	LF_ARGLIST: "LF_ARGLIST",
	LF_FIELDLIST: "LF_FIELDLIST",
	LF_ARRAY: "LF_ARRAY",
	LF_CLASS: "LF_CLASS",
	LF_STRUCTURE: "LF_STRUCTURE",
	LF_INTERFACE: "LF_INTERFACE",
	LF_UNION: "LF_UNION",
	LF_ENUM: "LF_ENUM",
	LF_TYPESERVER2: "LF_TYPESERVER2",
	LF_VFTABLE: "LF_VFTABLE",
	LF_VTSHAPE: "LF_VTSHAPE",
	LF_BITFIELD: "LF_BITFIELD",
	LF_FUNC_ID: "LF_FUNC_ID",
	LF_MFUNC_ID: "LF_MFUNC_ID",
	LF_BUILDINFO: "LF_BUILDINFO",
	LF_SUBSTR_LIST: "LF_SUBSTR_LIST",
	LF_STRING_ID: "LF_STRING_ID",
	LF_UDT_SRC_LINE: "LF_UDT_SRC_LINE",
	LF_UDT_MOD_SRC_LINE: "LF_UDT_MOD_SRC_LINE",
	LF_METHODLIST: "LF_METHODLIST",
	LF_PRECOMP: "LF_PRECOMP",
	LF_ENDPRECOMP: "LF_ENDPRECOMP",

	LF_BCLASS: "LF_BCLASS",
	LF_BINTERFACE: "LF_BINTERFACE",
	LF_VBCLASS: "LF_VBCLASS",
	LF_IVBCLASS: "LF_IVBCLASS",
	LF_VFUNCTAB: "LF_VFUNCTAB",
	LF_STMEMBER: "LF_STMEMBER",
	LF_METHOD: "LF_METHOD",
	LF_MEMBER: "LF_MEMBER",
	LF_NESTTYPE: "LF_NESTTYPE",
	LF_NESTTYPEEX: "LF_NESTTYPEEX",
	LF_ONEMETHOD: "LF_ONEMETHOD",
	LF_ENUMERATE: "LF_ENUMERATE",
	LF_INDEX: "LF_INDEX",
}
