#pragma once
#include "data_types.h"
// Generated by Ghidra

// Small version

inline void set_lava_walls() { return Resolve<void(*)()>("set_lava_walls")(); }
inline void give_mutation(body* param_1, int param_2, int* param_3, int param_4, bool param_5) { return Resolve<void(*)(body*, int, int*, int, bool)>("give_mutation")(param_1, param_2, param_3, param_4, param_5); }

inline void init_materials_list() { return Resolve<void(*)()>("init_materials_list")(); }
inline void init_mutations_list() { return Resolve<void(*)()>("init_mutations_list")(); }

inline void update_game(render_context* param_1, render_context* param_2, user_input* param_3) { return Resolve<void(*)(render_context*, render_context*, user_input*)>("update_game")(param_1, param_2, param_3); }
inline void update_cells(render_context* param_1, render_context* param_2, user_input* param_3) { return Resolve<void(*)(render_context*, render_context*, user_input*)>("update_cells")(param_1, param_2, param_3); }

inline void begin_trace_stage(char* param_1) { return Resolve<void(*)(char*)>("begin_trace_stage")(param_1); }
inline uint str_to_id(char* param_1) { return Resolve<uint(*)(char*)>("str_to_id")(param_1); }